with-expecter: true
filename: "{{.InterfaceName}}.go"
dir: "llm/mocks"
mockname: "{{.InterfaceName}}"
outpkg: "mocks"
inpackage: false
testonly: true
packages:
  github.com/adimarco/hive/llm:
    interfaces:
      AugmentedLLM: 