with-expecter: true
filename: "{{.InterfaceName}}.go"
dir: "llm/mocks"
mockname: "{{.InterfaceName}}"
outpkg: "mocks"
inpackage: false
disable-version-string: true
issue-845-fix: true
resolve-type-alias: false
packages:
  github.com/adimarco/hive/llm:
    interfaces:
      AugmentedLLM: {} 